//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Res.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} successfully !!!.
        /// </summary>
        public static string Action_Create_Success {
            get {
                return ResourceManager.GetString("Action_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited {0} successfully !!!.
        /// </summary>
        public static string Action_Edit_Success {
            get {
                return ResourceManager.GetString("Action_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOPDONG.
        /// </summary>
        public static string ContractTypeEnum_HopDong {
            get {
                return ResourceManager.GetString("ContractTypeEnum_HopDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHULUC.
        /// </summary>
        public static string ContractTypeEnum_Phuluc {
            get {
                return ResourceManager.GetString("ContractTypeEnum_Phuluc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string DepartmentGroupEnum_BANLE {
            get {
                return ResourceManager.GetString("DepartmentGroupEnum_BANLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrator.
        /// </summary>
        public static string DepartmentGroupEnum_TACNGHIEP {
            get {
                return ResourceManager.GetString("DepartmentGroupEnum_TACNGHIEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Address.
        /// </summary>
        public static string Location_Address {
            get {
                return ResourceManager.GetString("Location_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Area.
        /// </summary>
        public static string Location_Area {
            get {
                return ResourceManager.GetString("Location_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Code.
        /// </summary>
        public static string Location_Code {
            get {
                return ResourceManager.GetString("Location_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Fax.
        /// </summary>
        public static string Location_Fax {
            get {
                return ResourceManager.GetString("Location_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s In Area.
        /// </summary>
        public static string Location_InArea {
            get {
                return ResourceManager.GetString("Location_InArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Name.
        /// </summary>
        public static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s ParentCode.
        /// </summary>
        public static string Location_ParentCode {
            get {
                return ResourceManager.GetString("Location_ParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s Phone.
        /// </summary>
        public static string Location_Phone {
            get {
                return ResourceManager.GetString("Location_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Menu_City {
            get {
                return ResourceManager.GetString("Menu_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cities.
        /// </summary>
        public static string Menu_City_Create {
            get {
                return ResourceManager.GetString("Menu_City_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cities.
        /// </summary>
        public static string Menu_City_View {
            get {
                return ResourceManager.GetString("Menu_City_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Menu_Contract {
            get {
                return ResourceManager.GetString("Menu_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contracts.
        /// </summary>
        public static string Menu_Contract_Create {
            get {
                return ResourceManager.GetString("Menu_Contract_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contracts.
        /// </summary>
        public static string Menu_Contract_View {
            get {
                return ResourceManager.GetString("Menu_Contract_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Menu_Department {
            get {
                return ResourceManager.GetString("Menu_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Menu_Department_Create {
            get {
                return ResourceManager.GetString("Menu_Department_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Menu_Department_View {
            get {
                return ResourceManager.GetString("Menu_Department_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Menu_Document {
            get {
                return ResourceManager.GetString("Menu_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Documents.
        /// </summary>
        public static string Menu_Document_Create {
            get {
                return ResourceManager.GetString("Menu_Document_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Documents.
        /// </summary>
        public static string Menu_Document_View {
            get {
                return ResourceManager.GetString("Menu_Document_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Menu_Location {
            get {
                return ResourceManager.GetString("Menu_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Location.
        /// </summary>
        public static string Menu_Location_Create {
            get {
                return ResourceManager.GetString("Menu_Location_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Locations.
        /// </summary>
        public static string Menu_Location_View {
            get {
                return ResourceManager.GetString("Menu_Location_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Menu_Partner {
            get {
                return ResourceManager.GetString("Menu_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Partners.
        /// </summary>
        public static string Menu_Partner_Create {
            get {
                return ResourceManager.GetString("Menu_Partner_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Partners.
        /// </summary>
        public static string Menu_Partner_View {
            get {
                return ResourceManager.GetString("Menu_Partner_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Menu_Position {
            get {
                return ResourceManager.GetString("Menu_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string Menu_Staff {
            get {
                return ResourceManager.GetString("Menu_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Staffs.
        /// </summary>
        public static string Menu_Staff_Create {
            get {
                return ResourceManager.GetString("Menu_Staff_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Staffs.
        /// </summary>
        public static string Menu_Staff_View {
            get {
                return ResourceManager.GetString("Menu_Staff_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string PartnerHp_PartnerHpType_Current {
            get {
                return ResourceManager.GetString("PartnerHp_PartnerHpType_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string PartnerHp_PartnerHpType_Old {
            get {
                return ResourceManager.GetString("PartnerHp_PartnerHpType_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string SchedulePaymentEnum_MONTHLY {
            get {
                return ResourceManager.GetString("SchedulePaymentEnum_MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string SchedulePaymentEnum_QUARTERLY {
            get {
                return ResourceManager.GetString("SchedulePaymentEnum_QUARTERLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiYearly.
        /// </summary>
        public static string SchedulePaymentEnum_SEMIYEARLY {
            get {
                return ResourceManager.GetString("SchedulePaymentEnum_SEMIYEARLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string SchedulePaymentEnum_YEARLY {
            get {
                return ResourceManager.GetString("SchedulePaymentEnum_YEARLY", resourceCulture);
            }
        }
    }
}
